name: web
description: blog flutter web

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^1.0.0
  package_info: ^0.4.0
  simple_animations: ^2.2.1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/tab/account_selected.png
    - assets/tab/account_unselected.png
    - assets/tab/article_selected.png
    - assets/tab/article_unselected.png
    - assets/tab/category_selected.png
    - assets/tab/category_unselected.png
    - assets/tab/collection_selected.png
    - assets/tab/collection_unselected.png
    - assets/tab/other_selected.png
    - assets/tab/other_unselected.png
    - assets/tab/read_selected.png
    - assets/tab/read_unselected.png
    - assets/tab/timeline_selected.png
    - assets/tab/timeline_unselected.png

    - assets/avatar/avatar_male_30.png



