name: web
description: blog flutter web

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^1.0.0
  package_info: ^0.4.0
  simple_animations: ^2.2.1
  cupertino_icons: ^0.1.3
  provider: ^4.1.2
  dio: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/tab/article.png
    - assets/tab/study.png
    - assets/tab/other.png
    - assets/tab/read.png
    - assets/tab/collection.png

    - assets/avatar/avatar_male_30.png

    - assets/main_tab/article_selected.png
    - assets/main_tab/article_unselected.png
    - assets/main_tab/collection_selected.png
    - assets/main_tab/collection_unselected.png
    - assets/main_tab/read_selected.png
    - assets/main_tab/read_unselected.png
    - assets/main_tab/study_selected.png
    - assets/main_tab/study_unselected.png



